const projects = [
  {
    id: 1,
    filter: "filter-web",
    category: "Website",
    title: "Phoenix Soft Solutions Website",
    image: "assets/img/projects/Phoenix web 2.png",
    slides: [
      "assets/img/projects/Phoenix web 1.png",
      "assets/img/projects/Phoenix web 2.png",
      "assets/img/projects/Phoenix web 3.png",
    ],
    date: "Jul 2024 - Sep 2024",
    context: "Client Project",
    client: "",
    contributor_1_name: "Shammi Dodangoda",
    contributor_1_linkedin: "https://www.linkedin.com/in/shammi-saman-kumari/",
    contributor_2_name: "",
    contributor_2_linkedin: "",
    contributor_3_name: "",
    contributor_3_linkedin: "",
    demonstration: "",
    weburl: "https://phoenixsoftsolutions.com/",
    github: "https://github.com/tkdeshan/Phoenix-Soft-Solutions",
    technology: "MERN Stack",
    description:
      "Phoenix Soft Solutions is a technology company offering web, mobile, and software development services. This website showcases services and portfolio with a responsive design. It also includes an admin panel for updating projects, events, and customer reviews.",
  },
  {
    id: 2,
    filter: "filter-web",
    category: "Website",
    title: "Self Assistant AI Web App",
    image: "assets/img/projects/AI Web App 1.png",
    slides: ["assets/img/projects/AI Web App 1.png", "assets/img/projects/AI Web App 2.png"],
    date: "Jan 2024 - May 2024",
    context: "Independent Study",
    client: "",
    contributor_1_name: "Shammi Dodangoda",
    contributor_1_linkedin: "https://www.linkedin.com/in/shammi-saman-kumari/",
    contributor_2_name: "",
    contributor_2_linkedin: "",
    contributor_3_name: "",
    contributor_3_linkedin: "",
    demonstration: "",
    weburl: "https://self-assistant-ai-web-app.vercel.app/",
    github: "https://github.com/tkdeshan/Self_Assistant_AI_Web_App",
    technology: "MERN Stack | Gemini Api",
    description:
      "The AI Career Guidance and Knowledge Testing Web App provides personalized career advice and quizzes through a chat interface and dashboard. Users can explore career options, track quiz results, and receive tailored guidance to help them make informed decisions and improve their skills.",
  },
  {
    id: 3,
    filter: "filter-iot",
    category: "IoT",
    title: "Smart Home",
    image: "assets/img/projects/smart home 1.jpg",
    slides: [
      "assets/img/projects/smart home 1.jpg",
      "assets/img/projects/smart home 2.jpg",
      "assets/img/projects/smart home 3.png",
    ],
    date: "Feb 2024 - Mar 2024",
    context: "Prototype Development",
    client: "",
    contributor_1_name: "Shammi Dodangoda",
    contributor_1_linkedin: "https://www.linkedin.com/in/shammi-saman-kumari/",
    contributor_2_name: "",
    contributor_2_linkedin: "",
    contributor_3_name: "",
    contributor_3_linkedin: "",
    demonstration: "https://youtu.be/mFKJOkdENto?si=bA_bPPkvqOLS1big",
    weburl: "",
    github: "https://github.com/tkdeshan/Smart_Home/",
    technology: "IoT | C++",
    description:
      "This is the prototype of a smart home system that can securely control lights, switches, gates, and doors using a mobile phone. It utilizes sensors to detect objects and flames. The security status, sensor states, and other controlling element states can be viewed on the mobile phone.",
  },
  {
    id: 4,
    filter: "filter-es",
    category: "Embedded Systems",
    title: "Computer Controlled Power Supply",
    image: "assets/img/projects/ccps 3.png",
    slides: [
      "assets/img/projects/ccps 1.jpg",
      "assets/img/projects/ccps 6.png",
      "assets/img/projects/ccps 5.png",
      "assets/img/projects/ccps 4.png",
      "assets/img/projects/ccps 3.png",
    ],
    date: "Sep 2022 - Apr 2023",
    context: "Research Project",
    client: "",
    contributor_1_name: "Ramesh",
    contributor_1_linkedin: "",
    contributor_2_name: "Chamara",
    contributor_2_linkedin: "",
    contributor_3_name: "Masusha",
    contributor_3_linkedin: "",
    demonstration: "https://youtu.be/qlbTec5k6Nw?si=dy2EXsYNu9u4bX03",
    report: "https://drive.google.com/file/d/16DLSyZGm3z7cCXkWnOW1ap89l2XOnii-/view",
    weburl: "",
    github: "https://github.com/tkdeshan/Computer_Controlled_Power_Supply",
    technology: "Embedded Systems | C# | C++ | Innovation Development | Electronics",
    description:
      "This power supply features a graphical user interface (GUI) that allows users to obtain variable voltages up to 12 V with 0.1 V resolution. It can measure resistor values and plot I-V characteristic curves for electronic components like resistors, diodes, and transistors. The GUI facilitates command input and output display, including measured values and I-V curves.",
  },
];
